services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  tclsh:
    image: efrecon/tcl
    entrypoint: tclsh8.6
    restart: unless-stopped
    volumes:
      - /home/beholder/webapp:/usr/share/webapp:ro
    command: /usr/share/webapp/webapp.tcl
    environment:
      - VIRTUAL_HOST=whoami.local
#    expose:
#      - "80"
    healthcheck:
      test: ["CMD-SHELL", "tclsh8.6 /usr/share/webapp/healthcheck.tcl http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
